### ISSUE TITLE
Manuell inmatning på inputknapparna - oändlig

### ISSUE THREAD

**Issue by existenztim** [Medieinstitutet/fed22d-js-grundkurs-gruppuppgift-webbshop-team-n00bless#10]
Det går att mata in hur höga värden som helst i input knappen ifall man skriver manuellt och inte använder knapparna. Kanske lägga in en eventlisterner? Eller neka vid "lägg till" knappen om det är högre än 2 siffrigt.

**Comment by alexwallden** [comment]
La till ett tak på 2000 kr för totala summan i cartItems.
